apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app-deploy
spec:
  selector:
    matchLabels:
      app: autoscale-app
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: autoscale-app
    spec:
      containers:
      - image: 129800272058.dkr.ecr.us-east-1.amazonaws.com/nodejs:autoscale-1.0
        name: autoscale-app-containers
        ports:
        - containerPort: 9090