apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deploy
spec:
  selector:
    matchLabels:
      app: accounts-api
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      containers:
      - image: mohamedsahadkp/nodejs:accounts-1.0
        name: accounts-api-container
        ports:
        - containerPort: 3002