apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: {id: subnet-00000000}
      us-east-1b: {id: subnet-00000000}

nodeGroups:
  - name: ng-1-workers
    labels: {role: workers}
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-builders
    labels: {role: builders}
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true