apiVersion: v1
kind: Service
metadata:
  name: svc-api-user
  namespace: dev
spec:
  selector:
    app: deploy-api-user
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer