apiVersion: v1
kind: Service
metadata:
  name: svc-web-admin.yaml
  namespace: dev
spec:
  selector:
    app: deploy-web-admin
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer