apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: gcr.io/orbital-science-238912/nodejs:v1.0
        name: app-container
        ports:
        - containerPort: 8080