apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ms-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: *.com
      http:
        paths:
          - path: /api/users
            backend:
              serviceName: users-service
              servicePort: 3001
          - path: /api/accounts
            backend:
              serviceName: accounts-service
              servicePort: 3002